### ISSUE TITLE
Issues with `README.md` instructions

### ISSUE THREAD

**Issue by denwong47** [eneh4kene/movie_app#1]
Hi @eneh4kene just reviewing your repos and I can't help noticing that

- `requirements.txt` is missing with `requests` as dependency, and
- this is a CLI app that does not host anything on `localhost:5000`!

Just want to let you know, perhaps you would want to fix the README. :)

**Comment by eneh4kene** [comment]
Hi @denwong47 thank you for pointing out the issues. I mixed it up with the readme for a different project I was working on at the time. Please feel free to let me know of anything else.

**Comment by denwong47** [comment]
Thanks! Check your Cord.
